### ISSUE TITLE
Interactive Gradients - Better with outline over border

### ISSUE THREAD

**Issue by bebraw** [sarcadass/granim.js#1]
Hi,

I noticed your [last demo](https://sarcadass.github.io/granim.js/examples.html) would look a little better if you used the `outline` property over `border`. This way it doesn't offset the text as you click. Small thing but worth fixing.

**Comment by sarcadass** [comment]
The text offset is caused by the `font-weight` variation when the state CTA's `.active` class is toggled.
I will fix the text offset soon.

**Comment by bebraw** [comment]
Ok, cool.
