### ISSUE TITLE
Add commit message guidelines

### ISSUE THREAD

**Issue by pranaygp** [sarcadass/granim.js#13]
We should definitely add guidelines on what commit message should look like to the CONTRIBUTING.md 

This issue was inspired by commit messages on #12

**Comment by sarcadass** [comment]
I will update the CONTRIBUTING.md to be more precise for contribution.

**Comment by sarcadass** [comment]
I updated it.
@pranaygp feel free to update it if you think it lacks informations.

**Comment by MorbidAngel71** [comment]
Transgender help

**Comment by pranaygp** [comment]
@sarcadass Can I be added as a contributor to your project. I can still contribute without doing so, but It'll be easier for me, given that I plan to contribute to your project quite frequently.

**Comment by pranaygp** [comment]
Other than that, I've commented on 2 typos in your edits. Other than that, I think it's good to go, and I'll close it once those typos are fixed @sarcadass  :)

**Comment by sarcadass** [comment]
@pranaygp I sent you an invite to be a collaborator.
I will fix the typos now.

**Comment by MorbidAngel71** [comment]
Yes please help..need financial help from transgender admires

**Comment by sarcadass** [comment]
@MorbidAngel71 wtf ?
