### ISSUE TITLE
Add Test Cases

### ISSUE THREAD

**Issue by pranaygp** [sarcadass/granim.js#14]
We should definitely add test cases and set up CI and code coverage for project scalability.

@sarcadass Would you like to set up testing with Selenium as you mentioned in the contributing file, while I set up Travis and Codecov?

**Comment by pranaygp** [comment]
@sarcadass I just realized that setting up travis requires admin, so it may be better if you took care of that. Meanwhile, I can start implementing a test framework and write a few tests. I'll also implement code coverage after that. Sound good?

**Comment by sarcadass** [comment]
@pranaygp It's nice if you plan to implement the test framework, I don't have experience with Selenium but I already worked with Mocha and Chai. Do you think using Selenium or another test framework ?
Btw, I already have Travis CI and SauceLabs accounts.

I created a [Gitter channel](https://gitter.im/Granim-js/Contributors) if you want to discuss about it more in details.

**Comment by pranaygp** [comment]
Alright, let's move this to the gitter channel

**Comment by pranaygp** [comment]
I've added a few test cases to get us started. We just need to setup travis and codecov now to get CI working 👍 

@sarcadass can you please set up travis and codecov with the project?
