### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by pranaygp** [sarcadass/granim.js#15]
as @sarcadass indicated on [gitter](https://gitter.im/Granim-js/Contributors?utm_source=share-link&utm_medium=link&utm_campaign=share-link), we should add a changelog and keep track of our future updates on the project.

This should be as easy as looking at the commit log on github, and typing down a CHANGELOG

**Comment by sarcadass** [comment]
Fixed with 657f5dcaddfb6fe26507604109312003a2b11bec
