### ISSUE TITLE
Add example using reactjs

### ISSUE THREAD

**Issue by nerijusgood** [sarcadass/granim.js#16]
Hi,

I have been trying to use it with reactjs. Everytime I try to load it (on client side after content is loaded), I always get the `Uncaught TypeError: this.canvas.getContext is not a function(…)` error from Granim.js.

**Comment by pranaygp** [comment]
Since Granim tries to query the element directly from the DOM, you should use it within the `componentDidMount` lifecycle method of your component which is using this. 

This will ensure that the element actually exists in the DOM before Granim queries it.

**Comment by nerijusgood** [comment]
Thats what I did. I even tried with event listener:

componentDidMount() {
    window.addEventListener('load', this.handleBgEffects.bind(this))
  }

  handleBgEffects() {
    const granimInstance = new Granim({
      element: '#canvas-basic',
      name: 'basic-gradient',
      direction: 'left-right',
      opacity: [1, 1],
      isPausedWhenNotInView: true,
      states: {
        'default-state': {
          gradients: [
            ['#AA076B', '#61045F'],
            ['#02AAB0', '#00CDAC'],
            ['#DA22FF', '#9733EE'],
          ],
        },
      },
    })
    granimInstance()
  }

**Comment by pranaygp** [comment]
I don't believe you need an event listener for this. You also shouldn't invoke the instance directly. If I'm right, it should be pretty straightforward.

Try something like this and let me know if it works:

```Javascript
componentDidMount() {
   this.handleBgEffects();
  }

  handleBgEffects() {
    this.granimInstance = new Granim({
      element: '#canvas-basic',
      name: 'basic-gradient',
      direction: 'left-right',
      opacity: [1, 1],
      isPausedWhenNotInView: true,
      states: {
        'default-state': {
          gradients: [
            ['#AA076B', '#61045F'],
            ['#02AAB0', '#00CDAC'],
            ['#DA22FF', '#9733EE'],
          ],
        },
      },
    })
  }
```

**Comment by nerijusgood** [comment]
Still same issue:
`Dynamic page loading failed TypeError: this.canvas.getContext is not a function(…)`

**Comment by pranaygp** [comment]
Is this `componentDidMount ` in the same class that is rendering '# canvas-basic'?

**Comment by sarcadass** [comment]
@nerijusgood Do you have a `<canvas id="canvas-basic"></canvas>` set in your HTML?
I think the error is due to the fact that your `options.element` don't aim a `<canvas>` element.

**Comment by pranaygp** [comment]
@sarcadass It's a little different with React since he isn't directly writing HTML, rather using JSX and getting React to render these dynamically into the DOM

**Comment by sarcadass** [comment]
Yeah I know, I wasn't very clear in my last comment but is the element in
the DOM when the Granim instance is intiated?

Le 15 sept. 2016 9:42 PM, "Pranay Prakash" <notifications@github.com> a
écrit :

**Comment by pranaygp** [comment]
@nerijusgood I'm gonna close this issue since it's not directly related to the codebase, but let's continue this conversation on [gitter](https://gitter.im/Granim-js/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by nerijusgood** [comment]
@sarcadass you are right - I actually needed specifically use it on canvas element. I actually used regular div.

It works perfect with `<canvas id="canvas-basic"></canvas>`

Thank you.
