### ISSUE TITLE
Example "Gradients with an image mask": HTML code is wrong

### ISSUE THREAD

**Issue by M-arcus** [sarcadass/granim.js#19]
The class of the wrapper div `blov-logo` should be `bloc-logo`.
The id of the canvas should be `canvas-image-mask` instead of `canvas-basic`.

The correct HTML code is here: https://jsfiddle.net/3ehpuxew/1/

**Comment by sarcadass** [comment]
You're right. I will fix this soon, unless you want to submit a PR to fix this.

**Comment by M-arcus** [comment]
Will be submitting a PR asap
