### ISSUE TITLE
How to use with webpack? 

### ISSUE THREAD

**Issue by zaikin-andrew** [sarcadass/granim.js#22]
I've tried to use
```javascript
const Granim = require('granim/dist/granim.js');
```
but have empty object 
![image](https://cloud.githubusercontent.com/assets/7475399/18714734/6f714dae-801f-11e6-9b00-c6007eb0f6e3.png)

Thanks for assistance.

**Comment by pranaygp** [comment]
Just `require ('granim')` directly. Don't include the subpath.

**Comment by zaikin-andrew** [comment]
@pranaygp Thanks a lot! :)
