### ISSUE TITLE
pause() not always pause the animation

### ISSUE THREAD

**Issue by nejcgalof** [sarcadass/granim.js#23]
When I call `granimInstance.pause();` animation sometimes not paused, but if I check `granimInstance.isPaused`, this return _true_. 
This happend if I have one granim instance and have 5 buttons which 3 buttons for playing and changing states , one button for pause and one for clear. On different changes I must pressed button for pause twice, for working pause, but on the first time, `granimInstance.isPaused`, after  `granimInstance.pause();` return _true_. 
Any idea why is happening this, or how to fix cancel animation Frame work always on first time.

**Comment by sarcadass** [comment]
@nejcgalof  can you create a codePen for this please?
It will be easier to understand the problem.

**Comment by nejcgalof** [comment]
Here I write fast example from my biggest example.  [Codepen](http://codepen.io/anon/pen/QKgOPX) Maybe something not important in this page.
If click second icon, then pause(5), then again second and again pause. Then click last for clearing. Then again press second and then pause. Here you see, first time pause not working, second time work. This is my problem, why not pause animation sometimes? And sorry for bad example, but here I found a problem.

**Comment by pranaygp** [comment]
Just to add to what @nejcgalof said:

After clearing and hitting the second icon, then pausing, it doesn't actually pause. However, if you hit pause again, it does pause. This may have something to do with clearing ( played around with the codepen extensively)

@sarcadass any thoughts on what might be causing this?

**Comment by sarcadass** [comment]
@nejcgalof @pranaygp Weird behaviour indeed. I will investigate this when I'll have some time.
I keep you posted.

**Comment by sarcadass** [comment]
@nejcgalof I fixed the bug, can you confirm with the latest version of the lib please ?

**Comment by nejcgalof** [comment]
Yes, it works. Thank you.

**Comment by fcobcn** [comment]
I'm using the latest version (1.0.6) on a meteor app.
granimInstance.pause() doesn't work consistently, sometimes it does pause, but most of the time it doesn't.
Thanks for your help.

**Comment by pranaygp** [comment]
@fcobcn could you try recreating the issue and post code here or open a codepen. Would help us debug :) thanks

**Comment by pranaygp** [comment]
Also, for Android. How are you using granim? In a React Native app?

**Comment by fcobcn** [comment]
I will try to strip down the project as soon as posible, it may be related to how blaze templates work in meteor. Codepen is not relevant in this case. For android I'm using the cordova/phonegap compile functionality of meteor.
