### ISSUE TITLE
Apply granim.js as a <div> background rather than to a <canvas> element

### ISSUE THREAD

**Issue by tomheaps** [sarcadass/granim.js#24]
Great work. This is a feature request rather than an issue. 
What would be really useful is if you could apply the animated gradient as a background to a `<div>` rather than having to apply it to a `<canvas>` element - this way you could use `-webkit-background-clip:text` to produce text with an animated gradient fill, rather than having to photoshop a .png image with the transparent text cut out to layer over the gradient (as in the fourth example on your demo page)?

**Comment by sarcadass** [comment]
@tomheaps The entire lib is built upon the canvas API. So it won't be possible.

**Comment by makshh** [comment]
@tomheaps you can make animated gradient on text using only CSS (make background size like 200% 200% and animate it).
