### ISSUE TITLE
Question: Is it possible to use text as mask instead of image?

### ISSUE THREAD

**Issue by se-panfilov** [sarcadass/granim.js#25]
Subj.
It would be cool if it would be possible to use gradients with a text mask.

**Comment by pranaygp** [comment]
Supporting text masks causes a couple problems. Primarily, it involves rasterizing the text and adds a lot of bloat code for a very niche feature. 

As a suggestion, if you're looking to use static text as a mask then use Photoshop to make an image of nothing

**Comment by pranaygp** [comment]
Sorry, I meant to say, make an image with just the text and use that as your mask

**Comment by se-panfilov** [comment]
Yeah, I see, thanks
