### ISSUE TITLE
ie9 error

### ISSUE THREAD

**Issue by dmcanaveral** [sarcadass/granim.js#26]
Works fabulously everywhere except ie9. I'm getting an error saying "unable to get property 'remove' of undefined or null reference". This error breaks all my other javascript on the page. I read the comments on another browser issue about using a polyfill for older browsers.. How would I implement that and would it fix this error?

Thanks!

**Comment by pranaygp** [comment]
@dmcanaveral Thanks for reporting this bug. Could you please replicate this issue and post your console logs/backtrace?

**Comment by pranaygp** [comment]
Closing this issue since I haven't been able to recreate the issue. If it persists, please open a new issue :)
