### ISSUE TITLE
Granim's max width is 1024px which breaks mobile layouts.

### ISSUE THREAD

**Issue by stmalk** [sarcadass/granim.js#29]
Is there any way to set the width to a different value? Or make it flexible? Right now it goes down to 1024 when screen is resized and it breaks it for mobile screens that are smaller.

**Comment by sarcadass** [comment]
@stmalk you closed this issue, does it mean it wasn't a bug ?

Furthermore, I don't really see what you mean by making it "flexible".
You can simply set the size in CSS and the script is automatically appending the "height/width" attributes on the Canvas element onLoad and onResize.
I retested the home of the [docSite](https://sarcadass.github.io/granim.js/) on mobile and it's working well.

Do you have a exemple so I can reproduce ?

**Comment by stmalk** [comment]
Yes it was a css issue that I solved myself. The plugin does resize perfectly to any width.
