### ISSUE TITLE
Add Color-Stop-Position

### ISSUE THREAD

**Issue by SebaGnich** [sarcadass/granim.js#31]
Hello,

is it possible to add the feature with adding a color stop position to each color?

default:
`['#fff', '#000', '#f0f']`
optional:
`[{color: '#fff', pos: 0}, {color: '#000', pos: .3}, {color: '#f0f', pos: 1}]`

Thanks!

**Comment by sarcadass** [comment]
This is a good idea, I keep this in the features to add.

**Comment by 17090573124** [comment]
中文

**Comment by SebaGnich** [comment]
How is your plan in adding this? If you share your idea/solution, I could try to send you a PR then. 
If it's like I suggested, I could start right away :)

**Comment by sarcadass** [comment]
Oh great if you plan to add this ! :smile:.

I added you on the contributors channel on Gitter (https://gitter.im/Granim-js/Contributors).
We can talk more in details of the way to implement it.

**Comment by sarcadass** [comment]
Color-Stop-Position is now supported in V2.0.0 (#46)
