### ISSUE TITLE
Add "direction" in degrees

### ISSUE THREAD

**Issue by SebaGnich** [sarcadass/granim.js#32]
Hello!

It would be awesome, if you could extend the "direction" option with something like `130deg`.

Thank you! :)

**Comment by sarcadass** [comment]
It may be quite complicated to implement because there is no way to to it with the native canvas API.
I keep this as a feature to add if possible because it's a good idea.

**Comment by sarcadass** [comment]
Custom directions are now available in V2.0.0 (#46), you can't express them in degrees but you have full control of the gradient direction.
