### ISSUE TITLE
Fully dispose Granim to avoid memory leak in SPA

### ISSUE THREAD

**Issue by eirikurn** [sarcadass/granim.js#34]
Every Granim instance is registering events on window. These are currently not cleaned up, ie when calling pause or clear. So after navigating a few pages, there are still references to old granim instances and canvas elements. Resize and scroll performance may also be affected.

It would be great to have a .dispose() method to clean up the granim instance completely.

**Comment by sarcadass** [comment]
I will investigate this problem and provide a fix in the next version I'm planning to release soon.

**Comment by sarcadass** [comment]
I added a new `destroy()` method to remove the events listeners when you want to fully dispose a granim instance.

**Comment by eirikurn** [comment]
Awesome. Thank you so much for maintaining this awesome library! :)
