### ISSUE TITLE
Using on repeated elements

### ISSUE THREAD

**Issue by kaleidografik** [sarcadass/granim.js#37]
Hello. Is it possible to use Granim on multiple repeated elements within a page? Currently it only works on the first element, unless I define multiple instances of the init script to target different selectors?

```
// init
var newInstance = new Granim({
    element: '.gradient-bg',
    defaultStateName: 'state-1,
    direction: 'left-right',
    opacity: [1,1,1,1],
    isPausedWhenNotInView: true,
        states : {
            "state-1": {
                gradients: [
                    ['#AA076B', '#61045F'],
                    ['#02AAB0', '#00CDAC']
	        ],
	        transitionSpeed: 2500
           }
    }
});
```

**Comment by sarcadass** [comment]
You can't aim multiple nodes within the same instance, you will have to create a Granim instance for each canvas nodes.

[You can see how to easily do it on this pen.](https://jsfiddle.net/benjaminb/fvuxoe3n/)

(Small detail but you forgot to close the string for the `defaultStateName` value and you set 4 values for the opacity array but you only have two colors for your gradients [it will still work though]).
