### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'getElement' of null" Vue.js 2 - nuxt

### ISSUE THREAD

**Issue by Cactusx09** [sarcadass/granim.js#40]
![image](https://user-images.githubusercontent.com/9021479/44048398-e10359ea-9f39-11e8-8105-5b5269ee0d3c.png)

**Comment by sarcadass** [comment]
Hello,
I need more info to understand what's happening here.
Can you send your javascript code where you init Granim?

Even better, can you reproduce this bug on codepen or else? So I can debug.

**Comment by sarcadass** [comment]
@Cactusx09 Without further info from your part and the impossibility of reproducing the bug on my side, I close this issue.
