### ISSUE TITLE
Can we change de transitionSpeed dynamically?

### ISSUE THREAD

**Issue by psntr** [sarcadass/granim.js#43]
Is there an option/method like the changeState to change de transitionSpeed of a given state?

`granimInstance.changeTransitionSpeedState('default-state', 3000);
`

**Comment by sarcadass** [comment]
There is no method to change it, however you can mutate the state property to change it.
It has one drawback thought, it will need to finish the actual transition to update the transition speed.
[You can see an example here](https://jsfiddle.net/benjaminb/vcdpL3kt/).

**Comment by psntr** [comment]
Thank you for providing a working example. I see the downside. But anyway thank you again
