### ISSUE TITLE
HSLA support?

### ISSUE THREAD

**Issue by octoxalis** [sarcadass/granim.js#44]
Nice soft, and useful!
Looking at the doc and the code, I see there's no support for HSL/HSLA colors but only in Hexa.
Could you provide an HSL to RGB module to be able to define gradients with HSL/HSLA?

**Comment by sarcadass** [comment]
Currently, the only color syntax allowed is Hexadecimal.
I am working on a new version that will accept Hex, RGB, RGBA and HSL/HSLA.
