### ISSUE TITLE
Glitch on Safari when the Canvas is updated too often/quickly

### ISSUE THREAD

**Issue by rhanb** [sarcadass/granim.js#47]
Hi @sarcadass ,

This issue is not related to the new version (congrats by the way 🎉 ).

I encountered this issue when I was working on my personal website.
To give more context, I was trying to change the gradients using the `customDirection` property when the user is `panning` an element. Basically I was updating the `gradient` direction from a mouse event position. (You can try it out here: https://rhanb.me/) 

It works great, except on `Safari` and after digging a bit into this issue I found out that you apply the function `clearRect(0, 0, this.x1, this.y1)` twice when the `changeDirection` is called and when the `makeGradient` is called.

By removing the one of `makeGradient` everything works fine:

```javascript
var gradient = this.setDirection();
	var elToSetClassOnClass = document.querySelector(this.elToSetClassOn).classList;
	var i = 0;
	// this.context.clearRect(0, 0, this.x1, this.y1);

	if (this.image) {
		this.context.drawImage(
			this.imageNode,
			this.imagePosition.x,
			this.imagePosition.y,
			this.imagePosition.width,
			this.imagePosition.height
		);
	}
       ....
```

I'm not doing a PR because I wanted your feedback first; removing this line could break something?

**Comment by rhanb** [comment]
UPDATE:

even when removing all `clearRect` calls, the glitch still occurs. Need to deep dive to find solution

**Comment by rhanb** [comment]
This issue is due to the `animation` itself. Since it uses the `requestionAnimationFrame`, changing customDirection too quickly will make it glitch on Safari.

To avoid this issue you should `pause` the animation before updating the customDirection and `play` it again once you called the `changeDirection` function.

**Comment by sarcadass** [comment]
Hey @rhanb,
I tried to reproduce the bug on Safari by visiting [https://rhanb.me/](https://rhanb.me/), but everything looks fine.
Did you resolve the bug?
Can you reproduce the bug on [jsfiddle](https://jsfiddle.net/)?

**Comment by rhanb** [comment]
Hi @sarcadass ,

Yep I managed to fix the issue when i'm updating the customDirection I'm calling the `pause` function and then `play` once the new custom direction is applied.

I reproduced the bug right here: https://granim-safari-issue.stackblitz.io
