### ISSUE TITLE
Just for to understand!

### ISSUE THREAD

**Issue by giusbome** [sarcadass/granim.js#48]
Hi,
Is it possible to offer newcomers like me a very basic explanation of how to use your code?
I would like to have the description of each complete passage, how and where to add the code.
es: Where to insert the unzipped folder? - How to retrieve .js and .css files? - What to write on the html page?
I'm sorry, I tried to enter the codes that appear in the Tabs, but there was no result.
Thank you!

**Comment by sarcadass** [comment]
Hello @giusbome,
[I created a basic project using granim here.](https://codesandbox.io/s/ww9mj730x5)
You can download it by clicking on the download icon in the header to see how it works.
(note: the 'package.json' file is useless here).
