### ISSUE TITLE
How to add more background images like slides

### ISSUE THREAD

**Issue by mansres** [sarcadass/granim.js#49]
First Thanks for this wonderful job. Really I like to start using this plugin.

I need like this function. could you please add this features, it would be awesome. 

` image: {
        source: ['./Content/img/bgImage1.png', './Content/img/bgImage2.png'],
        blendingMode: 'multiply'
    },`
Thanks Team.

**Comment by sarcadass** [comment]
Hello @mansres ,
Unfortunately I don't plan to add this.
The core concept of this lib is to help quickly implement gradient based animations.

If you want to create a slider composed of images, there is plenty of js libraries that do this very well.
