### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by kounelios13** [sarcadass/granim.js#50]
Hello.I fount this library today.I was wondering.Is it possible to integrate it in an angular 2+ project.
If yes then how?

Thank you for your time

**Comment by sarcadass** [comment]
Hello @kounelios13,
With the help of this [article](https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af), I was able to create an [Angular basic project using Granim](https://codesandbox.io/s/o7lyv3o73q).

**Comment by sarcadass** [comment]
@kounelios13 Did my answer resolved your problem?
I'm closing the ticket now as it is not a bug.
