### ISSUE TITLE
Text Input Option

### ISSUE THREAD

**Issue by mapodev** [sarcadass/granim.js#9]
Could you add a text option which will be rendered in the middle of that canvas? Also an option for font and font-familiy + color.

**Comment by sarcadass** [comment]
I really want this lib to be focused on gradients animations, adding these options will break this rule and add more complexity (I will also have to add options to handle the alignment, the style...).

Furthemore, you can already do it in pure HTML / CSS, check the demo [here](https://sarcadass.github.io/granim.js/examples.html#canvas-interactive).
